### ISSUE TITLE
"The keyword 'integrated security' is not supported on this platform."

### ISSUE THREAD

**Issue by malachib** [emonney/QuickApp#11]
the dotnet restore & npm install work successfully, but when trying to run the app on macOS, this happens:

```
crit: QuickApp.Startup[101]
      Error whilst creating and seeding database
System.AggregateException: One or more errors occurred. (The keyword 'integrated security' is not supported on this platform.) ---> System.NotSupportedException: The keyword 'integrated security' is not supported on this platform.
   at System.Data.SqlClient.SqlConnectionString..ctor(String connectionString)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous)
   at System.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(DbConnectionPoolKey key, DbConnectionPoolGroupOptions poolOptions, DbConnectionOptions& userConnectionOptions)
   at System.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key)
   at System.Data.SqlClient.SqlConnection.set_ConnectionString(String value)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.<MigrateAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at DAL.DatabaseInitializer.<SeedAsync>d__4.MoveNext() in /Users/malachi/Projects/playground/playground.c#/src/PGC-14/Angular4/QuickApp/src/DAL/DatabaseInitializer.cs:line 46
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at QuickApp.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, IDatabaseInitializer databaseInitializer, ILoggerFactory loggerFactory) in /Users/malachi/Projects/playground/playground.c#/src/PGC-14/Angular4/QuickApp/src/QuickApp/Startup.cs:line 286
---> (Inner Exception #0) System.NotSupportedException: The keyword 'integrated security' is not supported on this platform.
   at System.Data.SqlClient.SqlConnectionString..ctor(String connectionString)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous)
   at System.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(DbConnectionPoolKey key, DbConnectionPoolGroupOptions poolOptions, DbConnectionOptions& userConnectionOptions)
   at System.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key)
   at System.Data.SqlClient.SqlConnection.set_ConnectionString(String value)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.<MigrateAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at DAL.DatabaseInitializer.<SeedAsync>d__4.MoveNext() in /Users/malachi/Projects/playground/playground.c#/src/PGC-14/Angular4/QuickApp/src/DAL/DatabaseInitializer.cs:line 46<---


Unhandled Exception: System.AggregateException: One or more errors occurred. (The keyword 'integrated security' is not supported on this platform.) ---> System.NotSupportedException: The keyword 'integrated security' is not supported on this platform.
   at System.Data.SqlClient.SqlConnectionString..ctor(String connectionString)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous)
   at System.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(DbConnectionPoolKey key, DbConnectionPoolGroupOptions poolOptions, DbConnectionOptions& userConnectionOptions)
   at System.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key)
   at System.Data.SqlClient.SqlConnection.set_ConnectionString(String value)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.<MigrateAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at DAL.DatabaseInitializer.<SeedAsync>d__4.MoveNext() in /Users/malachi/Projects/playground/playground.c#/src/PGC-14/Angular4/QuickApp/src/DAL/DatabaseInitializer.cs:line 46
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at QuickApp.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, IDatabaseInitializer databaseInitializer, ILoggerFactory loggerFactory) in /Users/malachi/Projects/playground/playground.c#/src/PGC-14/Angular4/QuickApp/src/QuickApp/Startup.cs:line 291
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at QuickApp.Program.Main(String[] args) in /Users/malachi/Projects/playground/playground.c#/src/PGC-14/Angular4/QuickApp/src/QuickApp/Program.cs:line 28
```

**Comment by emonney** [comment]
Integrated Security in asp.net core for now is only available on Windows Platforms.
When running on other platforms use an actual "username" and "password" instead.

**Comment by malachib** [comment]
BOOM!!  that issue is closed CUZ YOU SAY SO!
hilarious
thanks for the response though, it does point me in the right direction

**Comment by emonney** [comment]
lol, feel free to reopen this if this is still an issue.
