### ISSUE TITLE
dotnet ef migrations : Unable to retrieve project metadata

### ISSUE THREAD

**Issue by thanhnx94** [emonney/QuickApp#65]
dotnet ef database update no update database sql local
C:\Users\THANH\Documents\Visual Studio 2017\Projects\TestLan2\TestLan2\TestLan2>dotnet ef migrations add Init -p DAL -c DBContext -v
Using project 'DAL'.
Using startup project 'C:\Users\THANH\Documents\Visual Studio 2017\Projects\TestLan2\TestLan2\TestLan2\TestLan2.csproj'.
Writing 'obj\DAL.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\THANH\AppData\Local\Temp\tmp15C7.tmp /verbosity:quiet /nologo DAL
MSBUILD : error MSB1009: Project file does not exist.
Switch: DAL
Microsoft.EntityFrameworkCore.Tools.CommandException: Unable to retrieve project metadata. Ensure it's an MSBuild-based .NET Core project. If you're using custom BaseIntermediateOutputPath or MSBuildProjectExtensionsPath values, Use the --msbuildprojectextensionspath option.
   at Microsoft.EntityFrameworkCore.Tools.Project.FromFile(String file, String buildExtensionsDir, String framework, String configuration, String runtime)
   at Microsoft.EntityFrameworkCore.Tools.RootCommand.Execute()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
Unable to retrieve project metadata. Ensure it's an MSBuild-based .NET Core project. If you're using custom BaseIntermediateOutputPath or MSBuildProjectExtensionsPath values, Use the --msbuildprojectextensionspath option.

**Comment by emonney** [comment]
Try this: dotnet ef migrations add Init
Drop the extraneous flags.

**Comment by thanhnx94** [comment]
dotnet ef database update
Applying migration '20171217070146_InitData'.
Failed executing DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE TABLE [AppCustomers] (
    [Id] int NOT NULL IDENTITY,
    [Address] nvarchar(max) NULL,
    [City] nvarchar(50) NULL,
    [CreatedBy] nvarchar(256) NULL,
    [CreatedDate] datetime2 NOT NULL,
    [DateCreated] datetime2 NOT NULL,
    [DateModified] datetime2 NOT NULL,
    [Email] nvarchar(100) NULL,
    [Gender] int NOT NULL,
    [Name] nvarchar(100) NOT NULL,
    [PhoneNumber] varchar(30) NULL,
    [UpdatedBy] nvarchar(256) NULL,
    [UpdatedDate] datetime2 NOT NULL,
    CONSTRAINT [PK_AppCustomers] PRIMARY KEY ([Id])
);
System.Data.SqlClient.SqlException (0x80131904): There is already an object named 'AppCustomers' in the database.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
ClientConnectionId:26d55bf2-7dea-41f7-a7f5-f046c27e6ed5
Error Number:2714,State:6,Class:16
There is already an object named 'AppCustomers' in the database.

**Comment by IngoManthey** [comment]
@thanhnx94 
first delete the existing database or give it another name (ConnectionString)

**Comment by thanhnx94** [comment]
@IngoManthey 

Yes, I have changed and the server did not have database at run to create error, you should test and run dotnet ef database update see

**Comment by emonney** [comment]
See this for topics on aspnetcore migrations: https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations

**Comment by fasteddys** [comment]
I have the same problem in core 6.0.1
