### ISSUE TITLE
Why http://localhost:5000/dist/main-client.js a status of 404 (Not Found) ?

### ISSUE THREAD

**Issue by gro22** [emonney/QuickApp#8]

**Comment by gro22** [comment]
similar to main-client.js 404 Not Found issue.
Started a new project using the template. 
(It had OpenIddict issue, but solved by executing "dotnet restore" 
command in each project folder).
While the site is running, it got stuck at show "App is Loading...". Chrome browser shows "main-client.js 404 Not Found".
from
https://marketplace.visualstudio.com/items?itemName=adentum.QuickApp-ASPNETCoreAngularXProjectTemplate

**Comment by ritwickdey** [comment]
Probably you are in production environment. Set `ASPNETCORE_ENVIRONMENT` environment to `Development`. then try again. 

Alternatively, enter `dotnet  publish` then `dotnet run`...... 

Hopefully that will work

**Comment by emonney** [comment]
Did you by chance update to Webpack3?
The template is updated to v1.5. Packages are now locked to their specific versions to avoid updates in dependencies from breaking the template.
Your situation likely falls in this category. Get the latest version

**Comment by MOstafaMRady** [comment]
That worked for me
Set ASPNETCORE_ENVIRONMENT environment to Development

**Comment by eolarte** [comment]
Hi, I'm getting this error, but in mi case it's working with ASPNETCORE_ENVIRONMENT setted it in production. :(

**Comment by emonney** [comment]
@eolarte What errors are you getting? Please check the logs folder.

**Comment by eolarte** [comment]
Yes, let me give you more information. 
As i see it could be a problem with Webpack version or something of that.
- I downloaded the latest version and I ran it with f5.
- On the client side I got this error:
![capture](https://user-images.githubusercontent.com/14997286/34725010-744676ee-f52e-11e7-9efc-c1ae47ff2762.PNG)
Failed to load resource: the server responded with a status of 500 (Internal Server Error) main-client.js
Failed to load resource: the server responded with a status of 500 (Internal Server Error) vendor.js 
- The entries in the log file are:
2018-01-09T10:12:51.1187910-03:00 0HLANCANRLF7G:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:63992/   (ca22a1cb)
2018-01-09T10:12:51.9380784-03:00 0HLANCANRLF7G:00000001 [INF] Executing action method "Quick_Application1.Controllers.HomeController.Index (Quick_Application1)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-01-09T10:12:59.2367151-03:00 0HLANCANRLF7G:00000001 [INF] Executing ViewResult, running view at path "/Views/Home/Index.cshtml". (9707eebe)
2018-01-09T10:13:01.0571456-03:00 0HLANCANRLF7G:00000001 [INF] Executed action "Quick_Application1.Controllers.HomeController.Index (Quick_Application1)" in 9221.551ms (afa2e885)
2018-01-09T10:13:01.0665208-03:00 0HLANCANRLF7G:00000001 [INF] Request finished in 10001.3407ms 200 text/html; charset=utf-8 (791a596a)
2018-01-09T10:13:01.1128091-03:00 0HLANCANRLF7H:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:63992/dist/vendor.css?v=hbPnXv2O-_3ON5HfeJc41hq_S1jpB8g6S5D92Gr1wlQ   (ca22a1cb)
2018-01-09T10:13:01.1191993-03:00 0HLANCANRLF7G:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:63992/dist/vendor.js?v=KTbG8orBqXYcqt1brf70VwUoUxlTF_bMfvrXbFAFMCo   (ca22a1cb)
2018-01-09T10:13:01.1250557-03:00 0HLANCANRLF7I:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:63992/dist/main-client.js?v=aEqrvN7YVHMUyENbCORkAcab2OpuPo9claHGTB0TeLU   (ca22a1cb)
2018-01-09T10:13:02.2250060-03:00  [ERR]  (00000000)
2018-01-09T10:13:02.2724243-03:00  [ERR] C:\Users\Eduin.Olarte\Source\repos\Quick Application1\Quick Application1\Quick_Application1\node_modules\webpack\lib\ModuleFilenameHelpers.js:115
			`// module chunks = ${module.mapChunks(c => c.id).join(" ")}`
                                ^ (17738259)
2018-01-09T10:13:02.3137929-03:00  [ERR] TypeError: module.mapChunks is not a function
    at Object.createFooter (C:\Users\Eduin.Olarte\Source\repos\Quick Application1\Quick Application1\Quick_Application1\node_modules\webpack\lib\ModuleFilenameHelpers.js:115:33)
    at sourceMap.sourcesContent.sourceMap.sourcesContent.map (C:\Users\Eduin.Olarte\Source\repos\Quick Application1\Quick Application1\Quick_Application1\node_modules\webpack\lib\SourceMapDevToolPlugin.js:161:150)
    at Array.map (<anonymous>)
    at C:\Users\Eduin.Olarte\Source\repos\Quick Application1\Quick Application1\Quick_Application1\node_modules\webpack\lib\SourceMapDevToolPlugin.js:161:59
    at Array.forEach (<anonymous>)
    at Compilation.<anonymous> (C:\Users\Eduin.Olarte\Source\repos\Quick Application1\Quick Application1\Quick_Application1\node_modules\webpack\lib\SourceMapDevToolPlugin.js:151:11)
    at Compilation.applyPlugins1 (C:\Users\Eduin.Olarte\node_modules\tapable\lib\Tapable.js:75:14)
    at self.applyPluginsAsync.err (C:\Users\Eduin.Olarte\node_modules\webpack\lib\Compilation.js:639:11)
    at Compilation.applyPluginsAsyncSeries (C:\Users\Eduin.Olarte\node_modules\tapable\lib\Tapable.js:131:46)
    at self.applyPluginsAsync.err (C:\Users\Eduin.Olarte\node_modules\webpack\lib\Compilation.js:635:10) (e7a89feb)
2018-01-09T10:13:02.7011043-03:00 0HLANCANRLF7G:00000002 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The connection with the server was terminated abnormally
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---

**Comment by dhavalsp** [comment]
> Yes, let me give you more information.
> As i see it could be a problem with Webpack version or something of that.
> 
> * I downloaded the latest version and I ran it with f5.
> * On the client side I got this error:
>   ![capture](https://user-images.githubusercontent.com/14997286/34725010-744676ee-f52e-11e7-9efc-c1ae47ff2762.PNG)
>   Failed to load resource: the server responded with a status of 500 (Internal Server Error) main-client.js
>   Failed to load resource: the server responded with a status of 500 (Internal Server Error) vendor.js
> * The entries in the log file are:
>   2018-01-09T10:12:51.1187910-03:00 0HLANCANRLF7G:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:63992/   (ca22a1cb)
>   2018-01-09T10:12:51.9380784-03:00 0HLANCANRLF7G:00000001 [INF] Executing action method "Quick_Application1.Controllers.HomeController.Index (Quick_Application1)" with arguments (null) - ModelState is Valid (ba7f4ac2)
>   2018-01-09T10:12:59.2367151-03:00 0HLANCANRLF7G:00000001 [INF] Executing ViewResult, running view at path "/Views/Home/Index.cshtml". (9707eebe)
>   2018-01-09T10:13:01.0571456-03:00 0HLANCANRLF7G:00000001 [INF] Executed action "Quick_Application1.Controllers.HomeController.Index (Quick_Application1)" in 9221.551ms (afa2e885)
>   2018-01-09T10:13:01.0665208-03:00 0HLANCANRLF7G:00000001 [INF] Request finished in 10001.3407ms 200 text/html; charset=utf-8 (791a596a)
>   2018-01-09T10:13:01.1128091-03:00 0HLANCANRLF7H:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:63992/dist/vendor.css?v=hbPnXv2O-_3ON5HfeJc41hq_S1jpB8g6S5D92Gr1wlQ   (ca22a1cb)
>   2018-01-09T10:13:01.1191993-03:00 0HLANCANRLF7G:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:63992/dist/vendor.js?v=KTbG8orBqXYcqt1brf70VwUoUxlTF_bMfvrXbFAFMCo   (ca22a1cb)
>   2018-01-09T10:13:01.1250557-03:00 0HLANCANRLF7I:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:63992/dist/main-client.js?v=aEqrvN7YVHMUyENbCORkAcab2OpuPo9claHGTB0TeLU   (ca22a1cb)
>   2018-01-09T10:13:02.2250060-03:00  [ERR]  (00000000)
>   2018-01-09T10:13:02.2724243-03:00  [ERR] C:\Users\Eduin.Olarte\Source\repos\Quick Application1\Quick Application1\Quick_Application1\node_modules\webpack\lib\ModuleFilenameHelpers.js:115
>   `// module chunks = ${module.mapChunks(c => c.id).join(" ")}`
>   ^ (17738259)
>   2018-01-09T10:13:02.3137929-03:00  [ERR] TypeError: module.mapChunks is not a function
>   at Object.createFooter (C:\Users\Eduin.Olarte\Source\repos\Quick Application1\Quick Application1\Quick_Application1\node_modules\webpack\lib\ModuleFilenameHelpers.js:115:33)
>   at sourceMap.sourcesContent.sourceMap.sourcesContent.map (C:\Users\Eduin.Olarte\Source\repos\Quick Application1\Quick Application1\Quick_Application1\node_modules\webpack\lib\SourceMapDevToolPlugin.js:161:150)
>   at Array.map ()
>   at C:\Users\Eduin.Olarte\Source\repos\Quick Application1\Quick Application1\Quick_Application1\node_modules\webpack\lib\SourceMapDevToolPlugin.js:161:59
>   at Array.forEach ()
>   at Compilation. (C:\Users\Eduin.Olarte\Source\repos\Quick Application1\Quick Application1\Quick_Application1\node_modules\webpack\lib\SourceMapDevToolPlugin.js:151:11)
>   at Compilation.applyPlugins1 (C:\Users\Eduin.Olarte\node_modules\tapable\lib\Tapable.js:75:14)
>   at self.applyPluginsAsync.err (C:\Users\Eduin.Olarte\node_modules\webpack\lib\Compilation.js:639:11)
>   at Compilation.applyPluginsAsyncSeries (C:\Users\Eduin.Olarte\node_modules\tapable\lib\Tapable.js:131:46)
>   at self.applyPluginsAsync.err (C:\Users\Eduin.Olarte\node_modules\webpack\lib\Compilation.js:635:10) (e7a89feb)
>   2018-01-09T10:13:02.7011043-03:00 0HLANCANRLF7G:00000002 [ERR] An unhandled exception has occurred while executing the request (cf926119)
>   System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The connection with the server was terminated abnormally
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
>   at System.Net.Http.WinHttpHandler.d__105.MoveNext()
>   --- End of inner exception stack trace ---


I am facing the same issue. I have updated the Webpack and then after my existing project start to create a problem. After any change, it just shows the App loading and console error: main-client.js 500 error. Please share some solution if you find it already.
