### ISSUE TITLE
npm fails on opening solution

### ISSUE THREAD

**Issue by mrichman** [emonney/QuickApp#9]
I just did a `git clone` on this project, and opened the .sln in VS 2017. I see a `npm-debug.log` file created and destroyed in a loop with this content:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\mrichman\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev-build' ]
2 info using npm@3.10.6
3 info using node@v7.9.0
4 verbose run-script [ 'predev-build', 'dev-build', 'postdev-build' ]
5 info lifecycle QuickApp@0.1.1~predev-build: QuickApp@0.1.1
6 silly lifecycle QuickApp@0.1.1~predev-build: no script for predev-build, continuing
7 info lifecycle QuickApp@0.1.1~dev-build: QuickApp@0.1.1
8 verbose lifecycle QuickApp@0.1.1~dev-build: unsafe-perm in lifecycle true
9 verbose lifecycle QuickApp@0.1.1~dev-build: PATH: C:\Users\mrichman\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\mrichman\Source\QuickApp\src\QuickApp\node_modules\.bin;C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.2;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\\MSBuild\15.0\bin;C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Program Files (x86)\iis express\PHP\v5.4;C:\Program Files (x86)\Google\Chrome\Application;C:\Program Files (x86)\Windows Resource Kits\Tools\;C:\devkit\mingw\bin;C:\devkit\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Users\mrichman\.dnx\bin;C:\code\bin;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft Team Foundation Server 2;C:\ProgramData\chocolatey\bin;C:\Program Files\OpenSSH-Win64;C:\Program Files (x86)\Bitvise SSH Client;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\vim\vim74;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Docker;C:\Program Files (x86)\Microsoft Team Foundation Server 2015 Power Tools\;C:\Program Files (x86)\Skype\Phone\;C:\ProgramData\Oracle\Java\javapath\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Go\bin;C:\Program Files\Amazon\AWSCLI\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Users\mrichman\.dnx\bin;C:\Program Files (x86)\Microsoft Team Foundation Server 2015 Power Tools;C:\Program Files\Sublime Text 3;C:\Program Files\nodejs;C:\Users\mrichman\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Vim\vim80;C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\Program Files (x86)\Microsoft VS Code\bin;C:\OpenSSL-Win32\bin;C:\Users\mrichman\AppData\Roaming\npm;C:\Users\mrichman\AppData\Local\atom\bin;C:\Users\mrichman\go\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\
10 verbose lifecycle QuickApp@0.1.1~dev-build: CWD: C:\Users\mrichman\Source\QuickApp\src\QuickApp
11 silly lifecycle QuickApp@0.1.1~dev-build: Args: [ '/d /s /c',
11 silly lifecycle   'node node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js' ]
12 silly lifecycle QuickApp@0.1.1~dev-build: Returned: code: 1  signal: null
13 info lifecycle QuickApp@0.1.1~dev-build: Failed to exec dev-build script
14 verbose stack Error: QuickApp@0.1.1 dev-build: `node node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\mrichman\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\mrichman\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid QuickApp@0.1.1
16 verbose cwd C:\Users\mrichman\Source\QuickApp\src\QuickApp
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mrichman\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev-build"
19 error node v7.9.0
20 error npm  v3.10.6
21 error code ELIFECYCLE
22 error QuickApp@0.1.1 dev-build: `node node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js`
22 error Exit status 1
23 error Failed at the QuickApp@0.1.1 dev-build script 'node node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the QuickApp package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs QuickApp
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls QuickApp
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by emonney** [comment]
Verify that you are running at least node 6.9.x and npm 3.x.x by running node -v and npm -v in a terminal/console window.
Then manually run the commands VisualStudio does for you.
1. npm install
2. npm run dev-build

**Comment by emonney** [comment]
Closing issue. Reopen if the issue remains.
